version: 2.1

description: |
  Ruby Linter for Circleci Orb: bash 
  Source: https://github.com/amyroi/circleci-ruby-linter

commands:
  brakeman:
    description: Run brakeman
    parameters:
      parallel:
        default: true
        description: brakeman vesion. default is latest
        type: boolean
    steps:
    - run:
        command: bundle exec brakeman -o brakeman-output.tabs --no-progress --separate-models
          --exit-on-warn
        name: Run brakeman
        parallel: << parameters.parallel >>
