version: 2.1

description: |
  Ruby Linter for Circleci Orb: bash 
  Source: https://github.com/amyroi/circleci-ruby-linter

commands:
  brakeman:
    description: Run brakeman
    parameters:
      parallel:
        default: true
        description: brakeman vesion. default is latest
        type: boolean
    steps:
    - run:
        command: bundle exec brakeman -o brakeman-output.tabs --no-progress --separate-models
          --exit-on-warn
        name: Run brakeman
        parallel: << parameters.parallel >>
  haml-lin:
    description: Run haml-lint
    parameters:
      paths:
        default: app/views
        description: haml-lint target paths. default is app/views
        type: string
    steps:
    - run:
        command: bundle exec haml-lint "<< parameters.paths >>"
        name: Run haml-lint
  reek:
    description: Run reek
    parameters:
      paths:
        default: app lib config spec bin db
        description: reek target paths. default is app lib config spec bin db
        type: string
    steps:
    - run:
        command: bundle exec reek -s "<< parameters.paths >>"
        name: Run reek
  stylelint:
    description: Run stylelint
    steps:
    - run:
        command: bin/yarn lint:style
        name: Run stylelint

