version: 2.1

description: |
  Ruby Linter for Circleci Orb: bash 
  Source: https://github.com/amyroi/circleci-ruby-linter

commands:
  brakeman:
    steps:
      - run:
          name: Run brakeman
          command:  bundle exec brakeman -o brakeman-output.tabs --no-progress --separate-models --exit-on-warn
          parallel: "<< parameters.parallel >>"
    parameters:
      parallel:
        type: boolean
        default: true
        description: "brakeman vesion. default is latest"