version: 2.1

description: |
  Ruby Linter for Circleci Orb: bash 
  Source: https://github.com/amyroi/circleci-ruby-linter

brakeman:
  orb:
    commands:
      brakeman:
        parameters:
          parallel:
            default: true
            description: brakeman vesion. default is latest
            type: boolean
        steps:
        - run:
            command: bundle exec brakeman -o brakeman-output.tabs --no-progress --separate-models
              --exit-on-warn
            name: Run brakeman
            parallel: << parameters.parallel >>
    description: |
      Run brakeman
    examples:
      basic_commands:
        description: Examples uses brakeman commands
        usage:
          jobs:
            build:
              docker:
              - image: circleci/ruby:2.6.3
              steps:
              - checkout
              - ruby-linter/brakeman
          orbs:
            ruby-linter: amyroi/ruby-linter@1.0.0
          version: 2.1
    version: 2.1
eslint: {}
haml-lint: {}
rails_best_practices: {}
reek: {}
rubocop:
  orb: {}
stylelint: {}